"""create listings table

Revision ID: d5fb95b3d4ea
Revises: 
Create Date: 2026-07-07 13:14:03.372527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5fb95b3d4ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_caption', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('furnishing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('listing_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('availability_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
